// <auto-generated />
namespace MVC_Evaluation_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserIsActive1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIsActive1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151648218_UserIsActive1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
